const seedAccounts=[{name:'@vico.creates',platform:'TikTok',followers:'24.8K',niche:'Creator productivity'},{name:'Vico Rico Studio',platform:'YouTube',followers:'8.2K',niche:'Behind the scenes'},{name:'@thevicoedit',platform:'Instagram',followers:'12.6K',niche:'Visual storytelling'},{name:'@rico.daily',platform:'TikTok',followers:'3.1K',niche:'Personal finance'}];
const seedNiches=[{name:'Creator productivity',description:'Systems, tools, and routines for making content consistently.',status:'active',accounts:2,updated:'Today'},{name:'Visual storytelling',description:'Practical frameworks for making ordinary moments memorable.',status:'active',accounts:1,updated:'Yesterday'},{name:'Behind the scenes',description:'The real process behind running a creative studio.',status:'idea',accounts:1,updated:'Jul 28'},{name:'Personal finance',description:'Simple money lessons for independent creators.',status:'idea',accounts:1,updated:'Jul 24'},{name:'Gaming news',description:'Fast takes on the latest releases and industry shifts.',status:'deprecated',accounts:0,updated:'Jul 10'}];
const accountIdeas=[
 {name:'Cleaning dental niche',description:'Cleaning and dental care content.',status:'idea'},
 {name:'Cooking videos niche',description:'Recipe, cooking, and food video content.',status:'idea'},
 {name:'Culture Page',description:'Culture, trends, and community conversations.',status:'idea'},
 {name:'AI Girl',description:'AI-generated girl character and lifestyle content.',status:'idea'},
 {name:'Restaurants Page',description:'Restaurant discoveries, reviews, and food spots.',status:'idea'},
 {name:'AI Cinematic Videos',description:'Cinematic short-form videos made with AI.',status:'idea'},
 {name:'Character Page',description:'A recurring character-led social account.',status:'idea'},
 {name:'Horror Stories',description:'Short horror stories and unsettling narratives.',status:'idea'},
 {name:'Breakup Stories',description:'Breakup stories, lessons, and emotional storytelling.',status:'idea'},
 {name:'Types of Relationships',description:'Different relationship dynamics and perspectives.',status:'idea'},
 {name:'Fitness Page',description:'Fitness routines, motivation, and transformation content.',status:'idea'},
 {name:'Looksmaxxing',description:'Grooming, style, and appearance-improvement content.',status:'idea'},
 {name:'AI ASMR Accounts',description:'AI-generated ASMR sounds and visual loops.',status:'idea'},
 {name:'Suno influencers — Create. Your Artist',description:'Influencer accounts built around Suno artists and music creation.',status:'idea'},
 {name:'RO anime',description:'Romanian anime culture, recommendations, and community content.',status:'idea'},
 {name:'Tech Gadgets and Consumer Electronics',description:'AI UGC for earbuds, smart home devices, projectors, ergonomic accessories, and productivity hardware.',notes:'A $1.1T global market with high-margin products and strong customer LTV. Use realistic unboxing videos in a home environment, with the character reacting to features and demonstrating real-world use. AI product rendering and multi-angle mockups help keep the product consistent. Estimated CPM: $5–$12.',status:'idea'},
 {name:'Obscure Pet Supplies',description:'Specialized content for reptiles, birds, small mammals, fish, and other exotic pets.',notes:'A large audience with very little AI UGC competition. Focus on gecko terrarium supplies, parrot enrichment toys, or saltwater reef aquarium equipment. These communities are passionate, specialized, and spend heavily on supplies. Estimated CPM: $4–$9.',status:'idea'},
 {name:'Specialized Software — B2B Adjacent',description:'Project management, design, automation, and CRM tools for small businesses.',notes:'Create 30-second stories where a character struggles with a manual process, discovers a specific workflow, and experiences relief from the time saved. Hooks should focus on a precise pain point, the mechanism that solves it, and an identity-level transformation. High annual customer value supports strong brand budgets.',status:'idea'},
 {name:'High-End Coffee and Tea',description:'Cinematic content for specialty coffee, tea, brewing gear, and morning rituals.',notes:'A $47B global market with an affluent, loyal 25–45 audience. Make the product the star: brewing process, product reveal, steam, coffee bloom, and sensory lifestyle context. Estimated CPM: $3–$7, with volume making up for the lower ceiling.',status:'idea'},
 {name:'Home Organization and Minimalism Products',description:'Before-and-after organization content featuring products that transform a space.',notes:'A $30B+ market with a large TikTok and YouTube audience. Show a character walking through a transformed space and demonstrating products. Save behavior is a major advantage: viewers save organization content for later, helping it continue distributing weeks after posting.',status:'idea'},
 {name:'Financial Education Tools and Investing Apps',description:'Budgeting apps, micro-investing, crypto portfolio trackers, and credit tools.',notes:'Make the hook measurable: a character discovers a financial mistake, uses the tool, and documents the improvement over a specific timeframe. Specific numbers are stronger than vague claims. Estimated CPM: $6–$14 because of high financial-product LTV.',status:'idea'},
 {name:'Language Learning Apps and Tools',description:'Aspirational content about learning a second language with apps and AI tools.',notes:'With 1.8B people learning a second language, competing apps and platforms have strong creator acquisition budgets. Show a failed traditional approach, introduce one mechanism such as spaced repetition or an AI conversation partner, and document measurable progress. The identity angle makes this content highly shareable.',status:'idea'},
 {name:'Sleep Optimization Products',description:'Sleep trackers, weighted blankets, supplements, blackout solutions, and mattress accessories.',notes:'Use specific before-and-after sleep experiences: waking at 3am, feeling exhausted, or losing afternoon focus. Show measurable changes rather than generic wellness claims. Estimated CPM: $5–$11, supported by the broad audience and high wellness LTV.',status:'idea'},
 {name:"Kids' Educational Technology",description:'Edtech tools for parents and children ages 3–12.',notes:'The parent is the character, not the child. Show the parent’s relief, surprise, and delight as the child genuinely engages and learns. The content appeals to parents who want to make smart development decisions. Estimated CPM: $7–$15.',status:'idea'},
 {name:'Mental Health and Therapy-Adjacent Apps',description:'Meditation, journaling, anxiety management, and CBT-inspired tools.',notes:'Approach sensitive topics through animated characters: show a recognizable anxiety experience, introduce a specific coping mechanism, and show emotional relief. Keep the content educational and avoid making medical promises. Estimated CPM: $5–$12.',status:'idea'},
 {name:'Sustainable and Eco Products',description:'Sustainable alternatives, environmental education, and values-led product content.',notes:'A $150B+ global market with a young, educated, highly vocal audience. Visualize the environmental impact of a conventional product beside its sustainable alternative. Values-driven sharing creates social currency and can turn moderate views into occasional breakout performance.',status:'idea'}
].map(n=>({...n,accounts:0,updated:'Just added'}));
let accounts=JSON.parse(localStorage.getItem('orbit-accounts')||'null')||seedAccounts;let storedNiches=JSON.parse(localStorage.getItem('orbit-niches')||'null');let niches=storedNiches||seedNiches;accountIdeas.forEach(idea=>{if(!niches.some(n=>n.name.toLowerCase()===idea.name.toLowerCase()))niches.push(idea)});niches.forEach(n=>{if(n.name==='RO anime')delete n.reference});localStorage.setItem('orbit-niches',JSON.stringify(niches));let accountPlatform='all',nicheStatus='all';
const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function save(){localStorage.setItem('orbit-accounts',JSON.stringify(accounts));localStorage.setItem('orbit-niches',JSON.stringify(niches));render()}
function platformLetter(p){return p==='Instagram'?'◎':p==='YouTube'?'▶':'♪'}
function render(){
 $('#total-accounts').textContent=accounts.length;$('#active-niches').textContent=niches.filter(n=>n.status==='active').length;$('#idea-niches').textContent=niches.filter(n=>n.status==='idea').length;$('#platform-count').textContent=new Set(accounts.map(a=>a.platform)).size;$('#nav-account-count').textContent=accounts.length;$('#nav-niche-count').textContent=niches.length;
 $('#account-preview').innerHTML=accounts.slice(0,4).map(a=>`<div class="account-item"><span class="platform-icon ${a.platform}">${platformLetter(a.platform)}</span><div class="account-info"><strong>${esc(a.name)}</strong><small>${a.platform} · ${esc(a.followers||'No follower data')}</small></div><span class="status-chip active">Connected</span></div>`).join('')||'<p class="empty">No accounts yet.</p>';
 let active=niches.filter(n=>n.status==='active').length, total=niches.length;$('#coverage-value').textContent=(total?Math.round(active/total*100):0)+'%';$('#coverage-bar').style.width=(total?active/total*100:0)+'%';$('#niche-summary').innerHTML=niches.slice(0,4).map(n=>`<div class="niche-row ${n.status}"><span></span><strong>${esc(n.name)}</strong><small>${n.status==='deprecated'?'Archived':n.accounts+' account'+(n.accounts===1?'':'s')}</small></div>`).join('')||'<p class="empty">No niches yet.</p>';
 const search=($('#account-search')?.value||'').toLowerCase();$('#accounts-table').innerHTML=accounts.filter(a=>(accountPlatform==='all'||a.platform===accountPlatform)&&(`${a.name} ${a.niche} ${a.platform}`).toLowerCase().includes(search)).map((a,i)=>`<tr><td><div class="table-account"><span class="platform-icon ${a.platform}">${platformLetter(a.platform)}</span>${esc(a.name)}</div></td><td>${a.platform}</td><td>${esc(a.followers||'—')}</td><td>${esc(a.niche||'—')}</td><td><span class="status-chip active">Connected</span></td><td><button class="action-menu" data-delete-account="${i}">•••</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching accounts.</td></tr>';
 const ns=($('#niche-search')?.value||'').toLowerCase();$('#niches-table').innerHTML=niches.filter(n=>(nicheStatus==='all'||n.status===nicheStatus)&&(`${n.name} ${n.description} ${n.notes||''}`).toLowerCase().includes(ns)).map((n,i)=>`<tr><td>${esc(n.name)}</td><td>${esc(n.description)}${n.notes?` <details class="notes-details"><summary>View notes</summary><p>${esc(n.notes)}</p></details>`:''}${n.reference?` <a class="reference-link" href="${esc(n.reference)}" target="_blank" rel="noreferrer">Reference ↗</a>`:''}</td><td>${n.accounts}</td><td>${n.updated}</td><td><span class="status-chip ${n.status}">${n.status[0].toUpperCase()+n.status.slice(1)}</span></td><td><button class="action-menu" data-delete-niche="${i}">•••</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching niches.</td></tr>';
}
function showView(view){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('#'+view+'-view').classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#breadcrumb').textContent=view[0].toUpperCase()+view.slice(1);$('#page-title').textContent=view==='overview'?'Your social orbit':view==='accounts'?'Accounts':'Niche board';if(view!=='overview')$('.page-head').classList.add('hidden');else $('.page-head').classList.remove('hidden');render()}
function openModal(type){$('#modal-backdrop').classList.remove('hidden');$('#account-fields').classList.toggle('hidden',type==='niche');$('#niche-fields').classList.toggle('hidden',type!=='niche');$('#modal-eyebrow').textContent=type==='niche'?'New niche':'New account';$('#modal-title').textContent=type==='niche'?'Add a niche':'Add an account';$('#modal-subtitle').textContent=type==='niche'?'Turn a content direction into a clear next step.':'Keep your social channels in one place.';$('#entity-form').dataset.type=type;$('#entity-form').reset()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)showView(nav.dataset.view);const target=e.target.closest('[data-view-target]');if(target)showView(target.dataset.viewTarget);if(e.target.id==='quick-add'||e.target.id==='accounts-add')openModal('account');if(e.target.id==='niches-add')openModal('niche');if(e.target.id==='modal-close'||e.target.id==='modal-backdrop')$('#modal-backdrop').classList.add('hidden');const da=e.target.closest('[data-delete-account]');if(da&&confirm('Remove this account?')){accounts.splice(+da.dataset.deleteAccount,1);save()}const dn=e.target.closest('[data-delete-niche]');if(dn&&confirm('Remove this niche?')){niches.splice(+dn.dataset.deleteNiche,1);save()}});
document.querySelector('#entity-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(e.target.dataset.type==='niche')niches.unshift({name:f.get('nicheName'),description:f.get('description')||'No description added yet.',status:f.get('status'),accounts:0,updated:'Just now'});else accounts.unshift({name:f.get('name'),platform:f.get('platform'),followers:f.get('followers'),niche:f.get('niche')});$('#modal-backdrop').classList.add('hidden');save()});
document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');accountPlatform=b.dataset.platform;render()}));document.querySelectorAll('.niche-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.niche-filter').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');nicheStatus=b.dataset.status;render()}));$('#account-search').addEventListener('input',render);$('#niche-search').addEventListener('input',render);render();
