const seedAccounts=[{name:'@vico.creates',platform:'TikTok',followers:'24.8K',niche:'Creator productivity'},{name:'Vico Rico Studio',platform:'YouTube',followers:'8.2K',niche:'Behind the scenes'},{name:'@thevicoedit',platform:'Instagram',followers:'12.6K',niche:'Visual storytelling'},{name:'@rico.daily',platform:'TikTok',followers:'3.1K',niche:'Personal finance'}];
const seedFormats=[{name:'AI UGC product demo',notes:'Character introduces the product, demonstrates one use case, and shows the result in a short continuous sequence.',status:'active',updated:'Today'},{name:'Unboxing and first reaction',notes:'Open the product in a realistic environment, react to the key feature, and end with a clear reason to try it.',status:'idea',updated:'Today'},{name:'Before and after transformation',notes:'Show a specific starting problem, introduce the product or process, then reveal the measurable change.',status:'active',updated:'Yesterday'},{name:'Problem → mechanism → relief',notes:'Start with a precise pain point, reveal the mechanism that solves it, and show the emotional payoff.',status:'idea',updated:'Yesterday'},{name:'Cinematic product reveal',notes:'Let the product be the star with close-ups, movement, atmosphere, texture, and lifestyle context.',status:'idea',updated:'Jul 30'},{name:'Character-led story',notes:'Use a recurring character who faces a relatable situation, makes a discovery, and changes by the end.',status:'idea',updated:'Jul 28'},{name:'Educational comparison',notes:'Compare a conventional option with a better alternative using simple visuals and one memorable takeaway.',status:'idea',updated:'Jul 27'},{name:'Aesthetic ASMR loop',notes:'Build a satisfying visual and sound loop around preparation, texture, movement, or a repeatable ritual.',status:'idea',updated:'Jul 25'},{name:'Girls listening to music — UGC',notes:'A girl listens to a song in a relatable setting and posts a natural reaction, lip-sync, mood moment, or lifestyle clip. Keep it casual and native to short-form platforms so the music feels discovered rather than advertised.',status:'idea',updated:'Just added'},{name:'Retargeting video — warm audience',notes:'Create a 9:16, 30-second retargeting video for warm viewers who watched the product video but did not buy. Use a slower pace and a best-friend-giving-advice tone in a warm couch setting. Hook: address the objection directly, such as “I know $49 seems like a lot for a cream, but...”. Add a review screenshot-style overlay for social proof, soft scarcity such as “We only make 200 batches per month”, and CTA: “Link in bio — first 50 get 20% off.”',status:'idea',updated:'Just added'}];
const seedTrends=[{title:'Girls listening to music UGC',platform:'TikTok',notes:'Natural listening moments, reactions, lip-syncs, and mood clips that feel native to short-form video.',status:'new'},{title:'AI cinematic product reveals',platform:'Multi-platform',notes:'Short cinematic clips that make an ordinary product feel premium through atmosphere, texture, and movement.',status:'watching'},{title:'Saveable before-and-after content',platform:'Instagram',notes:'Transformation posts that give viewers a reason to save the post and come back to it later.',status:'new'}];
const seedPlans=[{title:'Music that makes a morning better',account:'@vico.creates',format:'Girls listening to music — UGC',date:'2026-08-02',status:'planned'},{title:'One product, three real-life use cases',account:'Vico Rico Studio',format:'AI UGC product demo',date:'2026-08-04',status:'idea'},{title:'The satisfying desk reset',account:'@thevicoedit',format:'Before and after transformation',date:'2026-08-06',status:'ready'}];
const seedPrompts=[{name:'UGC Creative Director System',category:'System prompt',text:`You are the Creative Director and Lead Producer at a UGC agency specializing in Shopify DTC brands.

TOOLS AVAILABLE:
- Higgsfield MCP for video/image generation
- Soul Characters for consistent avatars
- Marketing Studio for virality scoring

WORKFLOW:
1. Receive client brief → extract product angles and audience pain points
2. Research winning hooks in niche → write 5 script variations
3. Generate or select Soul Character → match to target demographic
4. Batch-generate videos using UGC preset → 9:16, 15-30 sec
5. Score each video with virality predictor → rank 1-10
6. Deliver with A/B test recommendations and platform specs

CONSTRAINTS:
- Never sound corporate. UGC must feel shot on iPhone by a real person
- Every script needs a pattern interrupt in the first 3 seconds
- Include subtle imperfections: natural lighting, slight hand shake, background noise suggestion
- Always generate 3 hook variations per concept
- Maintain brand kit colors and fonts in text overlays when specified`},{name:'Competitor Analysis Battlecard',category:'Research',text:`Analyze the UGC strategy for [COMPETITOR BRAND] in the [NICHE] space.

Find:
1. Top 3 performing ad angles from their TikTok / Instagram ad library
2. Hook patterns they repeat
3. Visual aesthetics: lighting, setting, and wardrobe
4. Call-to-action structures
5. Gaps — what are they NOT doing that we can own?

Output a Creative Battlecard with 5 counter-angles that position [CLIENT BRAND] as the fresh alternative.`},{name:'Batch Product Video Generator',category:'Production',text:`Generate 5 product showcase videos for [PRODUCT].

Format: 9:16, 15 seconds
Model: Seedance or Kling — choose the best motion quality
Style: UGC preset

ANGLE 1: Unboxing surprise
ANGLE 2: Day-in-the-life integration
ANGLE 3: Before / after transformation
ANGLE 4: POV: you finally found the product that...
ANGLE 5: Friend recommendation, over-the-shoulder shot style

Use Soul Character "sarah_skincare_01". Natural bathroom setting. Morning light. iPhone aesthetic. Generate all 5 in parallel and return URLs.`},{name:'Product Reference Scene',category:'Image template',text:`Use the uploaded image as the only product reference. Preserve the exact product shape, materials, logo placement, colors, and proportions.

Create a realistic [ASPECT RATIO] lifestyle scene for [PRODUCT] in [SETTING]. Show [ACTION / USE CASE] with natural lighting, believable shadows, and a premium but human feel. Keep the product clearly recognizable and avoid adding extra logos or text.`},{name:'Four-Panel Product Campaign',category:'Image template',text:`Create a four-panel promotional storyboard for [BRAND] and [PRODUCT].

Panel 1: pattern-breaking hero image
Panel 2: product close-up with the key mechanism
Panel 3: real-life use case with [TARGET AUDIENCE]
Panel 4: result, proof point, and space for a CTA

Use one consistent visual identity, [BRAND COLORS], [FONT STYLE], coherent product details, and editorial lighting. Keep each panel easy to crop for social formats.`},{name:'Consistent Character Lifestyle Set',category:'Character template',text:`Use [CHARACTER REFERENCE] as the only identity reference. Create a consistent character across 4 vertical lifestyle scenes: [LOCATION 1], [LOCATION 2], [LOCATION 3], and [LOCATION 4].

Keep facial identity, hair, wardrobe logic, body proportions, and age consistent. Make the poses candid and imperfect, with natural expressions, realistic lighting, and enough negative space for short-form text overlays.`},{name:'Seedance UGC Video Prompt',category:'Video template',text:`Generate a [DURATION]-second vertical 9:16 UGC video for [PRODUCT] using a consistent [CHARACTER].

Beat 1 — first 3 seconds: pattern interrupt with [HOOK]
Beat 2 — show the specific pain point in [SETTING]
Beat 3 — reveal the product and demonstrate [USE CASE]
Beat 4 — show proof or a believable before / after
Beat 5 — finish with [CTA]

Use natural camera movement, subtle hand shake, believable timing, realistic background audio, and imperfect iPhone-style lighting. Keep the product identity consistent in every shot.`}];
const seedNiches=[{name:'Creator productivity',description:'Systems, tools, and routines for making content consistently.',status:'active',accounts:2,updated:'Today'},{name:'Visual storytelling',description:'Practical frameworks for making ordinary moments memorable.',status:'active',accounts:1,updated:'Yesterday'},{name:'Behind the scenes',description:'The real process behind running a creative studio.',status:'idea',accounts:1,updated:'Jul 28'},{name:'Personal finance',description:'Simple money lessons for independent creators.',status:'idea',accounts:1,updated:'Jul 24'},{name:'Gaming news',description:'Fast takes on the latest releases and industry shifts.',status:'deprecated',accounts:0,updated:'Jul 10'}];
const accountIdeas=[
 {name:'Cleaning dental niche',description:'Cleaning and dental care content.',status:'idea'},
 {name:'Cooking videos niche',description:'Recipe, cooking, and food video content.',status:'idea'},
 {name:'Culture Page',description:'Culture, trends, and community conversations.',status:'idea'},
 {name:'AI Girl',description:'AI-generated girl character and lifestyle content.',status:'idea'},
 {name:'Restaurants Page',description:'Restaurant discoveries, reviews, and food spots.',status:'idea'},
 {name:'AI Cinematic Videos',description:'Cinematic short-form videos made with AI.',status:'idea'},
 {name:'Character Page',description:'A recurring character-led social account.',status:'idea'},
 {name:'Horror Stories',description:'Short horror stories and unsettling narratives.',status:'idea'},
 {name:'Breakup Stories',description:'Breakup stories, lessons, and emotional storytelling.',status:'idea'},
 {name:'Types of Relationships',description:'Different relationship dynamics and perspectives.',status:'idea'},
 {name:'Fitness Page',description:'Fitness routines, motivation, and transformation content.',status:'idea'},
 {name:'Looksmaxxing',description:'Grooming, style, and appearance-improvement content.',status:'idea'},
 {name:'AI ASMR Accounts',description:'AI-generated ASMR sounds and visual loops.',status:'idea'},
 {name:'Suno influencers — Create. Your Artist',description:'Influencer accounts built around Suno artists and music creation.',status:'idea'},
 {name:'RO anime',description:'Romanian anime culture, recommendations, and community content.',status:'idea'},
 {name:'Girls Listening to Music',description:'Girls listening to music and posting relatable reaction, mood, and lifestyle content.',notes:'Build accounts around natural music-listening moments: headphones, car rides, bedrooms, getting ready, studying, or walking. The content can use reactions, lip-syncs, mood edits, and song-discovery posts.',status:'idea'},
 {name:'Tech Gadgets and Consumer Electronics',description:'AI UGC for earbuds, smart home devices, projectors, ergonomic accessories, and productivity hardware.',notes:'A $1.1T global market with high-margin products and strong customer LTV. Use realistic unboxing videos in a home environment, with the character reacting to features and demonstrating real-world use. AI product rendering and multi-angle mockups help keep the product consistent. Estimated CPM: $5–$12.',status:'idea'},
 {name:'Obscure Pet Supplies',description:'Specialized content for reptiles, birds, small mammals, fish, and other exotic pets.',notes:'A large audience with very little AI UGC competition. Focus on gecko terrarium supplies, parrot enrichment toys, or saltwater reef aquarium equipment. These communities are passionate, specialized, and spend heavily on supplies. Estimated CPM: $4–$9.',status:'idea'},
 {name:'Specialized Software — B2B Adjacent',description:'Project management, design, automation, and CRM tools for small businesses.',notes:'Create 30-second stories where a character struggles with a manual process, discovers a specific workflow, and experiences relief from the time saved. Hooks should focus on a precise pain point, the mechanism that solves it, and an identity-level transformation. High annual customer value supports strong brand budgets.',status:'idea'},
 {name:'High-End Coffee and Tea',description:'Cinematic content for specialty coffee, tea, brewing gear, and morning rituals.',notes:'A $47B global market with an affluent, loyal 25–45 audience. Make the product the star: brewing process, product reveal, steam, coffee bloom, and sensory lifestyle context. Estimated CPM: $3–$7, with volume making up for the lower ceiling.',status:'idea'},
 {name:'Home Organization and Minimalism Products',description:'Before-and-after organization content featuring products that transform a space.',notes:'A $30B+ market with a large TikTok and YouTube audience. Show a character walking through a transformed space and demonstrating products. Save behavior is a major advantage: viewers save organization content for later, helping it continue distributing weeks after posting.',status:'idea'},
 {name:'Financial Education Tools and Investing Apps',description:'Budgeting apps, micro-investing, crypto portfolio trackers, and credit tools.',notes:'Make the hook measurable: a character discovers a financial mistake, uses the tool, and documents the improvement over a specific timeframe. Specific numbers are stronger than vague claims. Estimated CPM: $6–$14 because of high financial-product LTV.',status:'idea'},
 {name:'Language Learning Apps and Tools',description:'Aspirational content about learning a second language with apps and AI tools.',notes:'With 1.8B people learning a second language, competing apps and platforms have strong creator acquisition budgets. Show a failed traditional approach, introduce one mechanism such as spaced repetition or an AI conversation partner, and document measurable progress. The identity angle makes this content highly shareable.',status:'idea'},
 {name:'Sleep Optimization Products',description:'Sleep trackers, weighted blankets, supplements, blackout solutions, and mattress accessories.',notes:'Use specific before-and-after sleep experiences: waking at 3am, feeling exhausted, or losing afternoon focus. Show measurable changes rather than generic wellness claims. Estimated CPM: $5–$11, supported by the broad audience and high wellness LTV.',status:'idea'},
 {name:"Kids' Educational Technology",description:'Edtech tools for parents and children ages 3–12.',notes:'The parent is the character, not the child. Show the parent’s relief, surprise, and delight as the child genuinely engages and learns. The content appeals to parents who want to make smart development decisions. Estimated CPM: $7–$15.',status:'idea'},
 {name:'Mental Health and Therapy-Adjacent Apps',description:'Meditation, journaling, anxiety management, and CBT-inspired tools.',notes:'Approach sensitive topics through animated characters: show a recognizable anxiety experience, introduce a specific coping mechanism, and show emotional relief. Keep the content educational and avoid making medical promises. Estimated CPM: $5–$12.',status:'idea'},
 {name:'Sustainable and Eco Products',description:'Sustainable alternatives, environmental education, and values-led product content.',notes:'A $150B+ global market with a young, educated, highly vocal audience. Visualize the environmental impact of a conventional product beside its sustainable alternative. Values-driven sharing creates social currency and can turn moderate views into occasional breakout performance.',status:'idea'}
].map(n=>({...n,accounts:0,updated:'Just added'}));
let accounts=JSON.parse(localStorage.getItem('orbit-accounts')||'null')||seedAccounts;let storedNiches=JSON.parse(localStorage.getItem('orbit-niches')||'null');let niches=storedNiches||seedNiches;accountIdeas.forEach(idea=>{if(!niches.some(n=>n.name.toLowerCase()===idea.name.toLowerCase()))niches.push(idea)});niches.forEach(n=>{if(n.name==='RO anime')delete n.reference});localStorage.setItem('orbit-niches',JSON.stringify(niches));let formats=JSON.parse(localStorage.getItem('orbit-formats')||'null')||seedFormats;seedFormats.forEach(format=>{if(!formats.some(f=>f.name.toLowerCase()===format.name.toLowerCase()))formats.push(format)});localStorage.setItem('orbit-formats',JSON.stringify(formats));let trends=JSON.parse(localStorage.getItem('orbit-trends')||'null')||seedTrends;let plans=JSON.parse(localStorage.getItem('orbit-plans')||'null')||seedPlans;let prompts=JSON.parse(localStorage.getItem('orbit-prompts')||'null')||seedPrompts;seedPrompts.forEach(prompt=>{if(!prompts.some(p=>p.name.toLowerCase()===prompt.name.toLowerCase()))prompts.push(prompt)});localStorage.setItem('orbit-prompts',JSON.stringify(prompts));let accountPlatform='all',nicheStatus='all',formatStatus='all';
const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function save(){localStorage.setItem('orbit-accounts',JSON.stringify(accounts));localStorage.setItem('orbit-niches',JSON.stringify(niches));localStorage.setItem('orbit-formats',JSON.stringify(formats));localStorage.setItem('orbit-trends',JSON.stringify(trends));localStorage.setItem('orbit-plans',JSON.stringify(plans));localStorage.setItem('orbit-prompts',JSON.stringify(prompts));render()}
function platformLetter(p){return p==='Instagram'?'◎':p==='YouTube'?'▶':'♪'}
function render(){
 $('#total-accounts').textContent=accounts.length;$('#active-niches').textContent=niches.filter(n=>n.status==='active').length;$('#idea-niches').textContent=niches.filter(n=>n.status==='idea').length;$('#platform-count').textContent=new Set(accounts.map(a=>a.platform)).size;$('#nav-account-count').textContent=accounts.length;$('#nav-niche-count').textContent=niches.length;$('#nav-format-count').textContent=formats.length;$('#nav-prompt-count').textContent=prompts.length;
 $('#account-preview').innerHTML=accounts.slice(0,4).map(a=>`<div class="account-item"><span class="platform-icon ${a.platform}">${platformLetter(a.platform)}</span><div class="account-info"><strong>${esc(a.name)}</strong><small>${a.platform} · ${esc(a.followers||'No follower data')}</small></div><span class="status-chip active">Connected</span></div>`).join('')||'<p class="empty">No accounts yet.</p>';
 let active=niches.filter(n=>n.status==='active').length, total=niches.length;$('#coverage-value').textContent=(total?Math.round(active/total*100):0)+'%';$('#coverage-bar').style.width=(total?active/total*100:0)+'%';$('#niche-summary').innerHTML=niches.slice(0,4).map(n=>`<div class="niche-row ${n.status}"><span></span><strong>${esc(n.name)}</strong><small>${n.status==='deprecated'?'Archived':n.accounts+' account'+(n.accounts===1?'':'s')}</small></div>`).join('')||'<p class="empty">No niches yet.</p>';
 const search=($('#account-search')?.value||'').toLowerCase();$('#accounts-table').innerHTML=accounts.filter(a=>(accountPlatform==='all'||a.platform===accountPlatform)&&(`${a.name} ${a.niche} ${a.platform}`).toLowerCase().includes(search)).map((a,i)=>`<tr><td><div class="table-account"><span class="platform-icon ${a.platform}">${platformLetter(a.platform)}</span>${esc(a.name)}</div></td><td>${a.platform}</td><td>${esc(a.followers||'—')}</td><td>${esc(a.niche||'—')}</td><td><span class="status-chip active">Connected</span></td><td><button class="action-menu" data-delete-account="${i}">•••</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching accounts.</td></tr>';
 const ns=($('#niche-search')?.value||'').toLowerCase();$('#niches-table').innerHTML=niches.filter(n=>(nicheStatus==='all'||n.status===nicheStatus)&&(`${n.name} ${n.description} ${n.notes||''}`).toLowerCase().includes(ns)).map((n,i)=>`<tr><td>${esc(n.name)}</td><td>${esc(n.description)}${n.notes?` <details class="notes-details"><summary>View notes</summary><p>${esc(n.notes)}</p></details>`:''}${n.reference?` <a class="reference-link" href="${esc(n.reference)}" target="_blank" rel="noreferrer">Reference ↗</a>`:''}</td><td>${n.accounts}</td><td>${n.updated}</td><td><span class="status-chip ${n.status}">${n.status[0].toUpperCase()+n.status.slice(1)}</span></td><td><button class="action-menu" data-delete-niche="${i}">•••</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching niches.</td></tr>';
 const fs=($('#format-search')?.value||'').toLowerCase();$('#formats-table').innerHTML=formats.filter(f=>(formatStatus==='all'||f.status===formatStatus)&&(`${f.name} ${f.notes}`).toLowerCase().includes(fs)).map((f,i)=>`<tr><td>${esc(f.name)}</td><td><details class="notes-details"><summary>View notes</summary><p>${esc(f.notes)}</p></details></td><td><span class="status-chip ${f.status}">${f.status[0].toUpperCase()+f.status.slice(1)}</span></td><td>${f.updated}</td><td><button class="action-menu" data-delete-format="${i}">•••</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No matching content formats.</td></tr>';
 $('#prompt-grid').innerHTML=prompts.map((p,i)=>`<article class="prompt-card"><div class="prompt-card-head"><div><span class="prompt-category">${esc(p.category||'Custom prompt')}</span><h3>${esc(p.name)}</h3></div><button class="copy-prompt" data-copy-prompt="${i}">Copy</button></div><pre>${esc(p.text)}</pre><button class="quiet-button prompt-delete" data-delete-prompt="${i}">Remove prompt</button></article>`).join('')||'<p class="empty">No prompts saved yet.</p>';
 $('#trend-count').textContent=trends.filter(t=>t.status==='new').length;$('#planned-count').textContent=plans.filter(p=>p.status==='planned'||p.status==='idea').length;$('#ready-count').textContent=plans.filter(p=>p.status==='ready').length;$('#nav-plan-count').textContent=plans.filter(p=>p.status!=='posted').length;$('#trend-list').innerHTML=trends.map((t,i)=>`<div class="trend-card"><div class="trend-card-top"><span class="platform-label">${esc(t.platform)}</span><span class="trend-status ${t.status}">${t.status==='new'?'New':t.status==='watching'?'Watching':'Used'}</span></div><h3>${esc(t.title)}</h3><p>${esc(t.notes)}</p><div class="trend-actions"><button class="small-button" data-plan-trend="${i}">Plan content →</button><button class="quiet-button" data-delete-trend="${i}">Dismiss</button></div></div>`).join('')||'<p class="empty">No trends in your inbox yet.</p>';
 const statuses=[['idea','Ideas'],['planned','Planned'],['ready','Ready'],['posted','Posted']];$('#pipeline').innerHTML=statuses.map(([status,label])=>`<div class="pipeline-column"><div class="pipeline-heading"><span>${label}</span><b>${plans.filter(p=>p.status===status).length}</b></div>${plans.filter(p=>p.status===status).map(p=>`<div class="plan-card"><strong>${esc(p.title)}</strong><small>${esc(p.account||'Unassigned')}</small><span>${esc(p.format||'No format')} · ${p.date||'No date'}</span><button class="quiet-button" data-delete-plan="${plans.indexOf(p)}">Remove</button></div>`).join('')||'<div class="pipeline-empty">Nothing here yet</div>'}</div>`).join('');
}
function showView(view){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('#'+view+'-view').classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#breadcrumb').textContent=view[0].toUpperCase()+view.slice(1);$('#page-title').textContent=view==='overview'?'Your social orbit':view==='mission'?'Mission control':view==='accounts'?'Accounts':view==='niches'?'Niche board':view==='formats'?'Content formats':'Prompt library';if(view!=='overview')$('.page-head').classList.add('hidden');else $('.page-head').classList.remove('hidden');render()}
function openModal(type){$('#modal-backdrop').classList.remove('hidden');$('#account-fields').classList.toggle('hidden',type!=='account');$('#niche-fields').classList.toggle('hidden',type!=='niche');$('#format-fields').classList.toggle('hidden',type!=='format');$('#trend-fields').classList.toggle('hidden',type!=='trend');$('#plan-fields').classList.toggle('hidden',type!=='plan');$('#prompt-fields').classList.toggle('hidden',type!=='prompt');$('#modal-eyebrow').textContent=type==='niche'?'New niche':type==='format'?'New content format':type==='trend'?'Trend inbox':type==='plan'?'Plan content':type==='prompt'?'Prompt library':'New account';$('#modal-title').textContent=type==='niche'?'Add a niche':type==='format'?'Add a content format':type==='trend'?'Parse a trend':type==='plan'?'Plan a piece of content':type==='prompt'?'Add a prompt':'Add an account';$('#modal-subtitle').textContent=type==='niche'?'Turn a content direction into a clear next step.':type==='format'?'Save the structure and notes so you can reuse it.':type==='trend'?'Paste a trend, hook, or observation and save it for review.':type==='plan'?'Choose an account, format, and status for your next post.':type==='prompt'?'Save a reusable prompt for your creative workflow.':'Keep your social channels in one place.';if(type==='plan'){$('#content-account-select').innerHTML=accounts.map(a=>`<option>${esc(a.name)}</option>`).join('')||'<option>Unassigned</option>';$('#content-format-select').innerHTML=formats.map(f=>`<option>${esc(f.name)}</option>`).join('')||'<option>Unspecified</option>'}$('#entity-form').dataset.type=type;$('#entity-form').reset()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)showView(nav.dataset.view);const target=e.target.closest('[data-view-target]');if(target)showView(target.dataset.viewTarget);if(e.target.id==='quick-add'||e.target.id==='accounts-add')openModal('account');if(e.target.id==='niches-add')openModal('niche');if(e.target.id==='formats-add')openModal('format');if(e.target.id==='prompts-add')openModal('prompt');if(e.target.id==='trend-add'||e.target.id==='trend-add-inline')openModal('trend');if(e.target.id==='plan-add'||e.target.id==='plan-add-inline')openModal('plan');if(e.target.id==='modal-close'||e.target.id==='modal-backdrop')$('#modal-backdrop').classList.add('hidden');const da=e.target.closest('[data-delete-account]');if(da&&confirm('Remove this account?')){accounts.splice(+da.dataset.deleteAccount,1);save()}const dn=e.target.closest('[data-delete-niche]');if(dn&&confirm('Remove this niche?')){niches.splice(+dn.dataset.deleteNiche,1);save()}const df=e.target.closest('[data-delete-format]');if(df&&confirm('Remove this content format?')){formats.splice(+df.dataset.deleteFormat,1);save()}const dt=e.target.closest('[data-delete-trend]');if(dt&&confirm('Dismiss this trend?')){trends.splice(+dt.dataset.deleteTrend,1);save()}const dp=e.target.closest('[data-delete-plan]');if(dp&&confirm('Remove this planned content?')){plans.splice(+dp.dataset.deletePlan,1);save()}const dpr=e.target.closest('[data-delete-prompt]');if(dpr&&confirm('Remove this prompt?')){prompts.splice(+dpr.dataset.deletePrompt,1);save()}const cp=e.target.closest('[data-copy-prompt]');if(cp){navigator.clipboard?.writeText(prompts[+cp.dataset.copyPrompt].text);cp.textContent='Copied';setTimeout(()=>cp.textContent='Copy',1200)}const pt=e.target.closest('[data-plan-trend]');if(pt){openModal('plan');const trend=trends[+pt.dataset.planTrend];setTimeout(()=>{$('[name="contentTitle"]').value=trend.title},0)}});
document.querySelector('#entity-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(e.target.dataset.type==='niche')niches.unshift({name:f.get('nicheName'),description:f.get('description')||'No description added yet.',status:f.get('status'),accounts:0,updated:'Just now'});else if(e.target.dataset.type==='format')formats.unshift({name:f.get('formatName'),notes:f.get('formatNotes')||'No notes added yet.',status:f.get('formatStatus'),updated:'Just now'});else if(e.target.dataset.type==='trend')trends.unshift({title:f.get('trendTitle'),platform:f.get('trendPlatform'),notes:f.get('trendNotes')||'No notes added yet.',status:'new'});else if(e.target.dataset.type==='plan')plans.unshift({title:f.get('contentTitle'),account:f.get('contentAccount'),format:f.get('contentFormat'),date:f.get('publishDate'),status:f.get('contentStatus')});else if(e.target.dataset.type==='prompt')prompts.unshift({name:f.get('promptName'),category:f.get('promptCategory')||'Custom prompt',text:f.get('promptText')});else accounts.unshift({name:f.get('name'),platform:f.get('platform'),followers:f.get('followers'),niche:f.get('niche')});$('#modal-backdrop').classList.add('hidden');save()});
function buildResearchBrief(f){const brand=f.get('researchBrand')||'[BRAND NAME]',product=f.get('researchProduct')||'[PRODUCT NAME]',audience=f.get('researchAudience')||'[TARGET AUDIENCE]',price=f.get('researchPrice')||'[PRICE]',reviews=f.get('researchReviews')||'[PAIN POINTS FROM REVIEWS]';const hooks=[`I was today years old when I learned what ${product} actually does for ${audience}.`,`Stop scrolling if you are a ${audience} still struggling with ${reviews}.`,`POV: you finally found a ${product} that fits your real routine.`,`This ${price} product replaced my $500 routine.`,`The way my ${audience} changed after 1 week of ${product}.`];$('#research-output').innerHTML=`<div class="brief-head"><div><span class="eyebrow">Creative strategy brief</span><h3>${esc(brand)} × ${esc(product)}</h3></div><button class="quiet-button" type="button" id="copy-brief">Copy brief</button></div><div class="brief-block counter-block"><span class="brief-label">Counter-narrative</span><strong>Most competitors say “${esc(product)} gives instant results.” Find the contradiction: what are people wrong about, oversold on, or quietly frustrated by?</strong><p>Research the gap between the consensus promise and the lived experience in these reviews: ${esc(reviews)}</p></div><div class="brief-block"><span class="brief-label">Three angle directions</span><div class="angle-list"><div><b>01 · The contradiction</b><p>Challenge the category promise and show the unexpected reason the audience should care.</p></div><div><b>02 · The proof moment</b><p>Turn one specific pain point into a visual test with a measurable result.</p></div><div><b>03 · The identity shift</b><p>Show how using ${esc(product)} changes how ${esc(audience)} sees themselves.</p></div></div></div><div class="brief-block"><span class="brief-label">Hook variations</span><ol class="hook-list">${hooks.map(h=>`<li>${esc(h)}</li>`).join('')}</ol></div><div class="brief-block"><span class="brief-label">Shot list for each angle</span><div class="shot-list"><span>1. Pattern-break opening</span><span>2. Specific pain point</span><span>3. Product / mechanism reveal</span><span>4. Proof or before → after</span><span>5. Emotional payoff + CTA</span></div></div>`;$('#copy-brief').addEventListener('click',()=>{const text=`${brand} × ${product}\nCounter-narrative: What is this niche wrong about?\nHooks:\n${hooks.join('\n')}\nShot list: Pattern break → pain point → mechanism → proof → payoff`;navigator.clipboard?.writeText(text);$('#copy-brief').textContent='Copied'})}
document.querySelector('#research-form').addEventListener('submit',e=>{e.preventDefault();buildResearchBrief(new FormData(e.target))});
document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');accountPlatform=b.dataset.platform;render()}));document.querySelectorAll('.niche-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.niche-filter').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');nicheStatus=b.dataset.status;render()}));document.querySelectorAll('.format-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.format-filter').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');formatStatus=b.dataset.status;render()}));$('#account-search').addEventListener('input',render);$('#niche-search').addEventListener('input',render);$('#format-search').addEventListener('input',render);render();
